### ISSUE TITLE
 Image is not updated

### ISSUE THREAD

**Issue by Ron0815** [colinbendell/homebridge-blink-for-home#10]
Hello everybody,
as I already reported, I was able to get the plugin to work in the meantime. But now I found out that the picture in the thumbnail is only displayed correctly the first time, but is not updated afterwards. The display at the bottom right shows "now" every 10 seconds, but without showing the current situation in front of the camera. So the first picture will ne permanently repeated or such.
What can I do to solve this issue?
BEST REGARDS

**Comment by colinbendell** [comment]
Which version of the plugin are you running? What hardware do you have? Is there any notifications in the logs?

**Comment by MasterofKungfu9999** [comment]
I have the same issue and every time i want to watch the live picture the camera says "no answer", the camera doesn't answer. Version 3.5.10

**Comment by colinbendell** [comment]
Live view is not implemented. What hardware are you using? Can you share
the logs?

**Comment by MasterofKungfu9999** [comment]
I thougt liveview was implementet because the config shows "
Enable LiveView when clicking on a camera feed (experimental)".

I will so my very best to share some logs.

**Comment by MasterofKungfu9999** [comment]
Here is my log:

30.10.2020, 22:45:59 [Haustür] Starting video stream (1280x720, 30 fps, 299 kbps, 1378 mtu)...
30.10.2020, 22:45:59 [Haustür] [Video] Failed to start video stream: spawn ffmpeg ENOENT
30.10.2020, 22:46:02 [Haustür] GET /api/v3/accounts/36976/homescreen
30.10.2020, 22:46:02 [Haustür] GET /api/v1/accounts/36976/media/changed?since=1970-01-01T00:00:01+0000&page=1
30.10.2020, 22:46:12 [Haustür] GET /api/v3/accounts/36976/homescreen
30.10.2020, 22:46:22 [Haustür] GET /api/v3/accounts/36976/homescreen
30.10.2020, 22:46:22 [Haustür] GET /api/v1/accounts/36976/media/changed?since=1970-01-01T00:00:01+0000&page=1
30.10.2020, 22:46:32 [Haustür] GET /api/v3/accounts/36976/homescreen
30.10.2020, 22:46:42 [Haustür] GET /api/v3/accounts/36976/homescreen

**Comment by colinbendell** [comment]
Yea. I removed live view a view minor versions back because is was clearly more broken than experimental. 

Can you provide more logs going back further? Does it refresh the thumbnail on restart of the plug-in? Or does it only refresh when you invoke it manually?

**Comment by colinbendell** [comment]
Also - can you tell me if this happens when the system is armed or only
when unarmed?

**Comment by colinbendell** [comment]
I've added a diagnostic switch in the advanced settings. would you mind turning this on and sending me the diagnostic logs? (between ==== START DIAGNOSTIC and ==== END DIAGNOSTIC blocks). Feel free to email them to me directly

**Comment by MasterofKungfu9999** [comment]
I will do, but at the moment there is no update. i have to explain that i'm using hoobs. There are updates a little bit later.

**Comment by Ron0815** [comment]
I use Homebridge (latest version) on a RaspberryPi 3 B and have installed the blink-plugin (latest version) via Homebridge UI-X (latest version) in order to be able to use my Blink XT2 on Homekit.

**Comment by Ron0815** [comment]
And here is the log file:
Loading logs using "custom" method...
CMD: journalctl -o cat -n 500 -f -u homebridge

  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:42:48] [Blink] {"account":{"id":80325,"email_verified":true,"email_verification_required":true},"networks":[{"id":103215,"created_at":"2019-06-28T12:26:40+00:00","updated_at":"2020-10-30T16:27:55+00:00","name":"StationHome","time_zone":"Europe/Berlin","dst":true,"armed":true,"lv_save":false}],"sync_modules":[{"id":320349,"created_at":"2019-10-11T16:08:36+00:00","updated_at":"2020-10-31T10:13:21+00:00","onboarded":true,"status":"online","name":"My Blink Sync Module","serial":"XXXXXXXX","fw_version":"2.13.26","type":"sm1","last_hb":"2020-10-31T10:42:28+00:00","wifi_strength":4,"network_id":103215,"enable_temp_alerts":true,"local_storage_enabled":false,"local_storage_compatible":false,"local_storage_status":"unavailable"}],"cameras":[{"id":546462,"created_at":"2020-04-01T16:49:18+00:00","updated_at":"2020-10-31T09:55:54+00:00","name":"Blinker 1","serial":"681146121","fw_version":"2.151","type":"xt","enabled":false,"thumbnail":"/media/production/account/80325/network/103215/camera/546462/clip_LzawD7JN_2020_10_30__20_22PM","status":"done","battery":"ok","usage_rate":false,"network_id":103215,"issues":[],"signals":{"lfr":5,"wifi":2,"temp":67,"battery":3},"local_storage_enabled":false,"local_storage_compatible":false}],"sirens":[],"chimes":[],"video_stats":{"storage":0,"auto_delete_days":14,"auto_delete_day_options":[3,7,14,30,365]},"doorbell_buttons":[],"owls":[],"app_updates":{"message":"OK","code":103,"update_available":false,"update_required":false},"device_limits":{"camera":10,"chime":5,"doorbell_button":2,"owl":10,"siren":5,"total_devices":20},"whats_new":{"updated_at":20200924,"url":"https://updates.blinkforhome.com/"}}
[10/31/2020, 11:42:48] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:42:48] [Blink] 200 OK
[10/31/2020, 11:42:48] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:42:48 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'ulI5jxxqagRQa0aosIi3_9pdyHlbTSTColjM3fl0SWBScTQZdoAkCQ==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-04f57b6d4750e0f38',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:42:48] [Blink] {"limit":500,"purge_id":991893923,"refresh_count":0,"media":[]}
[10/31/2020, 11:42:58] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:42:58] [Blink] 200 OK
[10/31/2020, 11:42:58] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:42:58 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'xyUaJOCltw6WHD-nSgMoEA8zZ1grXav-MAHqGxB0qnkLTY9EQIGuGg==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-0294ed2caf1f46ca9',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:42:58] [Blink] {"account":{"id":80325,"email_verified":true,"email_verification_required":true},"networks":[{"id":103215,"created_at":"2019-06-28T12:26:40+00:00","updated_at":"2020-10-30T16:27:55+00:00","name":"StationHome","time_zone":"Europe/Berlin","dst":true,"armed":true,"lv_save":false}],"sync_modules":[{"id":320349,"created_at":"2019-10-11T16:08:36+00:00","updated_at":"2020-10-31T10:13:21+00:00","onboarded":true,"status":"online","name":"My Blink Sync Module","serial":"XXXXXXXX","fw_version":"2.13.26","type":"sm1","last_hb":"2020-10-31T10:42:28+00:00","wifi_strength":4,"network_id":103215,"enable_temp_alerts":true,"local_storage_enabled":false,"local_storage_compatible":false,"local_storage_status":"unavailable"}],"cameras":[{"id":546462,"created_at":"2020-04-01T16:49:18+00:00","updated_at":"2020-10-31T09:55:54+00:00","name":"Blinker 1","serial":"681146121","fw_version":"2.151","type":"xt","enabled":false,"thumbnail":"/media/production/account/80325/network/103215/camera/546462/clip_LzawD7JN_2020_10_30__20_22PM","status":"done","battery":"ok","usage_rate":false,"network_id":103215,"issues":[],"signals":{"lfr":5,"wifi":2,"temp":67,"battery":3},"local_storage_enabled":false,"local_storage_compatible":false}],"sirens":[],"chimes":[],"video_stats":{"storage":0,"auto_delete_days":14,"auto_delete_day_options":[3,7,14,30,365]},"doorbell_buttons":[],"owls":[],"app_updates":{"message":"OK","code":103,"update_available":false,"update_required":false},"device_limits":{"camera":10,"chime":5,"doorbell_button":2,"owl":10,"siren":5,"total_devices":20},"whats_new":{"updated_at":20200924,"url":"https://updates.blinkforhome.com/"}}
[10/31/2020, 11:43:08] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:43:08] [Blink] 200 OK
[10/31/2020, 11:43:08] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:43:08 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': '9PmrAXxEDFLknJnbpWYXQMFmbODu1X5Ge64jL1ayKv-w8JSEO8llXQ==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-021458bdd2db486b9',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:43:08] [Blink] {"account":{"id":80325,"email_verified":true,"email_verification_required":true},"networks":[{"id":103215,"created_at":"2019-06-28T12:26:40+00:00","updated_at":"2020-10-30T16:27:55+00:00","name":"StationHome","time_zone":"Europe/Berlin","dst":true,"armed":true,"lv_save":false}],"sync_modules":[{"id":320349,"created_at":"2019-10-11T16:08:36+00:00","updated_at":"2020-10-31T10:13:21+00:00","onboarded":true,"status":"online","name":"My Blink Sync Module","serial":"XXXXXXXX","fw_version":"2.13.26","type":"sm1","last_hb":"2020-10-31T10:42:28+00:00","wifi_strength":4,"network_id":103215,"enable_temp_alerts":true,"local_storage_enabled":false,"local_storage_compatible":false,"local_storage_status":"unavailable"}],"cameras":[{"id":546462,"created_at":"2020-04-01T16:49:18+00:00","updated_at":"2020-10-31T09:55:54+00:00","name":"Blinker 1","serial":"681146121","fw_version":"2.151","type":"xt","enabled":false,"thumbnail":"/media/production/account/80325/network/103215/camera/546462/clip_LzawD7JN_2020_10_30__20_22PM","status":"done","battery":"ok","usage_rate":false,"network_id":103215,"issues":[],"signals":{"lfr":5,"wifi":2,"temp":67,"battery":3},"local_storage_enabled":false,"local_storage_compatible":false}],"sirens":[],"chimes":[],"video_stats":{"storage":0,"auto_delete_days":14,"auto_delete_day_options":[3,7,14,30,365]},"doorbell_buttons":[],"owls":[],"app_updates":{"message":"OK","code":103,"update_available":false,"update_required":false},"device_limits":{"camera":10,"chime":5,"doorbell_button":2,"owl":10,"siren":5,"total_devices":20},"whats_new":{"updated_at":20200924,"url":"https://updates.blinkforhome.com/"}}
[10/31/2020, 11:43:08] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:43:08] [Blink] 200 OK
[10/31/2020, 11:43:08] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:43:08 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'K85j15fwqHhPc6hPZdr3SqsDmcTw1oNUMqFaU83qP4eXHM5TqPhiYQ==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-0434674833e8640e7',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:43:08] [Blink] {"limit":500,"purge_id":991893923,"refresh_count":0,"media":[]}
[10/31/2020, 11:43:18] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:43:18] [Blink] 200 OK
[10/31/2020, 11:43:18] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:43:18 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 's3Pptn7Rk-0y2ioYCzqHoDXCNQ6bXJSWD5afz2ZcX9nfq0JgGei5Ig==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-09563ee5c5148c712',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:43:18] [Blink] {"account":{"id":80325,"email_verified":true,"email_verification_required":true},"networks":[{"id":103215,"created_at":"2019-06-28T12:26:40+00:00","updated_at":"2020-10-30T16:27:55+00:00","name":"StationHome","time_zone":"Europe/Berlin","dst":true,"armed":true,"lv_save":false}],"sync_modules":[{"id":320349,"created_at":"2019-10-11T16:08:36+00:00","updated_at":"2020-10-31T10:13:21+00:00","onboarded":true,"status":"online","name":"My Blink Sync Module","serial":"XXXXXXXX","fw_version":"2.13.26","type":"sm1","last_hb":"2020-10-31T10:42:28+00:00","wifi_strength":4,"network_id":103215,"enable_temp_alerts":true,"local_storage_enabled":false,"local_storage_compatible":false,"local_storage_status":"unavailable"}],"cameras":[{"id":546462,"created_at":"2020-04-01T16:49:18+00:00","updated_at":"2020-10-31T09:55:54+00:00","name":"Blinker 1","serial":"681146121","fw_version":"2.151","type":"xt","enabled":false,"thumbnail":"/media/production/account/80325/network/103215/camera/546462/clip_LzawD7JN_2020_10_30__20_22PM","status":"done","battery":"ok","usage_rate":false,"network_id":103215,"issues":[],"signals":{"lfr":5,"wifi":2,"temp":67,"battery":3},"local_storage_enabled":false,"local_storage_compatible":false}],"sirens":[],"chimes":[],"video_stats":{"storage":0,"auto_delete_days":14,"auto_delete_day_options":[3,7,14,30,365]},"doorbell_buttons":[],"owls":[],"app_updates":{"message":"OK","code":103,"update_available":false,"update_required":false},"device_limits":{"camera":10,"chime":5,"doorbell_button":2,"owl":10,"siren":5,"total_devices":20},"whats_new":{"updated_at":20200924,"url":"https://updates.blinkforhome.com/"}}
[10/31/2020, 11:43:28] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:43:28] [Blink] 200 OK
[10/31/2020, 11:43:28] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:43:28 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'V-2gjBBQGCTNIiai3Eaw0ZxmHKCmOCFmGE98eA-WLJ8aZWyt6P-cgQ==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-0f373aeff7ee64139',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:43:28] [Blink] {"account":{"id":80325,"email_verified":true,"email_verification_required":true},"networks":[{"id":103215,"created_at":"2019-06-28T12:26:40+00:00","updated_at":"2020-10-30T16:27:55+00:00","name":"StationHome","time_zone":"Europe/Berlin","dst":true,"armed":true,"lv_save":false}],"sync_modules":[{"id":320349,"created_at":"2019-10-11T16:08:36+00:00","updated_at":"2020-10-31T10:13:21+00:00","onboarded":true,"status":"online","name":"My Blink Sync Module","serial":"XXXXXXXX","fw_version":"2.13.26","type":"sm1","last_hb":"2020-10-31T10:43:23+00:00","wifi_strength":4,"network_id":103215,"enable_temp_alerts":true,"local_storage_enabled":false,"local_storage_compatible":false,"local_storage_status":"unavailable"}],"cameras":[{"id":546462,"created_at":"2020-04-01T16:49:18+00:00","updated_at":"2020-10-31T09:55:54+00:00","name":"Blinker 1","serial":"681146121","fw_version":"2.151","type":"xt","enabled":false,"thumbnail":"/media/production/account/80325/network/103215/camera/546462/clip_LzawD7JN_2020_10_30__20_22PM","status":"done","battery":"ok","usage_rate":false,"network_id":103215,"issues":[],"signals":{"lfr":5,"wifi":2,"temp":67,"battery":3},"local_storage_enabled":false,"local_storage_compatible":false}],"sirens":[],"chimes":[],"video_stats":{"storage":0,"auto_delete_days":14,"auto_delete_day_options":[3,7,14,30,365]},"doorbell_buttons":[],"owls":[],"app_updates":{"message":"OK","code":103,"update_available":false,"update_required":false},"device_limits":{"camera":10,"chime":5,"doorbell_button":2,"owl":10,"siren":5,"total_devices":20},"whats_new":{"updated_at":20200924,"url":"https://updates.blinkforhome.com/"}}
[10/31/2020, 11:43:28] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:43:28] [Blink] 200 OK
[10/31/2020, 11:43:28] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:43:28 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'uNbEVLfH-G4RfgZWynm7Xquw4_JMGl9u7k8z6ssGsHpBO5tXDe4lEA==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-04f57b6d4750e0f38',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:43:28] [Blink] {"limit":500,"purge_id":991893923,"refresh_count":0,"media":[]}
[10/31/2020, 11:43:38] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:43:38] [Blink] 200 OK
[10/31/2020, 11:43:38] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:43:38 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': '7MibkQxNYXYfp4hiGE8B4sRvd4fe6NmtBnuZcs5aoHbIy5WCW8B0FQ==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-053060bc83780c2a4',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:43:38] [Blink] {"account":{"id":80325,"email_verified":true,"email_verification_required":true},"networks":[{"id":103215,"created_at":"2019-06-28T12:26:40+00:00","updated_at":"2020-10-30T16:27:55+00:00","name":"StationHome","time_zone":"Europe/Berlin","dst":true,"armed":true,"lv_save":false}],"sync_modules":[{"id":320349,"created_at":"2019-10-11T16:08:36+00:00","updated_at":"2020-10-31T10:13:21+00:00","onboarded":true,"status":"online","name":"My Blink Sync Module","serial":"XXXXXXXX","fw_version":"2.13.26","type":"sm1","last_hb":"2020-10-31T10:43:23+00:00","wifi_strength":4,"network_id":103215,"enable_temp_alerts":true,"local_storage_enabled":false,"local_storage_compatible":false,"local_storage_status":"unavailable"}],"cameras":[{"id":546462,"created_at":"2020-04-01T16:49:18+00:00","updated_at":"2020-10-31T09:55:54+00:00","name":"Blinker 1","serial":"681146121","fw_version":"2.151","type":"xt","enabled":false,"thumbnail":"/media/production/account/80325/network/103215/camera/546462/clip_LzawD7JN_2020_10_30__20_22PM","status":"done","battery":"ok","usage_rate":false,"network_id":103215,"issues":[],"signals":{"lfr":5,"wifi":2,"temp":67,"battery":3},"local_storage_enabled":false,"local_storage_compatible":false}],"sirens":[],"chimes":[],"video_stats":{"storage":0,"auto_delete_days":14,"auto_delete_day_options":[3,7,14,30,365]},"doorbell_buttons":[],"owls":[],"app_updates":{"message":"OK","code":103,"update_available":false,"update_required":false},"device_limits":{"camera":10,"chime":5,"doorbell_button":2,"owl":10,"siren":5,"total_devices":20},"whats_new":{"updated_at":20200924,"url":"https://updates.blinkforhome.com/"}}
[10/31/2020, 11:43:48] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:43:48] [Blink] 200 OK
[10/31/2020, 11:43:48] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:43:48 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'aI_4IJhVTH72XWFrRTuaoVqN7vWtyuHxdGWIjg0EI3SrsZebD2TmCg==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-00db64ff2b4d27031',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:43:49] [Blink] {"account":{"id":80325,"email_verified":true,"email_verification_required":true},"networks":[{"id":103215,"created_at":"2019-06-28T12:26:40+00:00","updated_at":"2020-10-30T16:27:55+00:00","name":"StationHome","time_zone":"Europe/Berlin","dst":true,"armed":true,"lv_save":false}],"sync_modules":[{"id":320349,"created_at":"2019-10-11T16:08:36+00:00","updated_at":"2020-10-31T10:13:21+00:00","onboarded":true,"status":"online","name":"My Blink Sync Module","serial":"XXXXXXXX","fw_version":"2.13.26","type":"sm1","last_hb":"2020-10-31T10:43:23+00:00","wifi_strength":4,"network_id":103215,"enable_temp_alerts":true,"local_storage_enabled":false,"local_storage_compatible":false,"local_storage_status":"unavailable"}],"cameras":[{"id":546462,"created_at":"2020-04-01T16:49:18+00:00","updated_at":"2020-10-31T09:55:54+00:00","name":"Blinker 1","serial":"681146121","fw_version":"2.151","type":"xt","enabled":false,"thumbnail":"/media/production/account/80325/network/103215/camera/546462/clip_LzawD7JN_2020_10_30__20_22PM","status":"done","battery":"ok","usage_rate":false,"network_id":103215,"issues":[],"signals":{"lfr":5,"wifi":2,"temp":67,"battery":3},"local_storage_enabled":false,"local_storage_compatible":false}],"sirens":[],"chimes":[],"video_stats":{"storage":0,"auto_delete_days":14,"auto_delete_day_options":[3,7,14,30,365]},"doorbell_buttons":[],"owls":[],"app_updates":{"message":"OK","code":103,"update_available":false,"update_required":false},"device_limits":{"camera":10,"chime":5,"doorbell_button":2,"owl":10,"siren":5,"total_devices":20},"whats_new":{"updated_at":20200924,"url":"https://updates.blinkforhome.com/"}}
[10/31/2020, 11:43:49] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:43:49] [Blink] 200 OK
[10/31/2020, 11:43:49] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:43:49 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'gt2HnjaVBvrq0Lcm2fP1ELpDetFP1NdP6oFvPQFE4k2jm7BUnvaAzw==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-0be600a9e21cba1ec',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:43:49] [Blink] {"limit":500,"purge_id":991893923,"refresh_count":0,"media":[]}
[10/31/2020, 11:43:59] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:43:59] [Blink] 200 OK
[10/31/2020, 11:43:59] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:43:59 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 't-XUIZ-N29FVmmUauj6mPYW3YhS-IkfIACI68s_C5FXadJ4SNx2o3g==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-0935309f2169e4f85',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:43:59] [Blink] {"account":{"id":80325,"email_verified":true,"email_verification_required":true},"networks":[{"id":103215,"created_at":"2019-06-28T12:26:40+00:00","updated_at":"2020-10-30T16:27:55+00:00","name":"StationHome","time_zone":"Europe/Berlin","dst":true,"armed":true,"lv_save":false}],"sync_modules":[{"id":320349,"created_at":"2019-10-11T16:08:36+00:00","updated_at":"2020-10-31T10:13:21+00:00","onboarded":true,"status":"online","name":"My Blink Sync Module","serial":"XXXXXXXX","fw_version":"2.13.26","type":"sm1","last_hb":"2020-10-31T10:43:23+00:00","wifi_strength":4,"network_id":103215,"enable_temp_alerts":true,"local_storage_enabled":false,"local_storage_compatible":false,"local_storage_status":"unavailable"}],"cameras":[{"id":546462,"created_at":"2020-04-01T16:49:18+00:00","updated_at":"2020-10-31T09:55:54+00:00","name":"Blinker 1","serial":"681146121","fw_version":"2.151","type":"xt","enabled":false,"thumbnail":"/media/production/account/80325/network/103215/camera/546462/clip_LzawD7JN_2020_10_30__20_22PM","status":"done","battery":"ok","usage_rate":false,"network_id":103215,"issues":[],"signals":{"lfr":5,"wifi":2,"temp":67,"battery":3},"local_storage_enabled":false,"local_storage_compatible":false}],"sirens":[],"chimes":[],"video_stats":{"storage":0,"auto_delete_days":14,"auto_delete_day_options":[3,7,14,30,365]},"doorbell_buttons":[],"owls":[],"app_updates":{"message":"OK","code":103,"update_available":false,"update_required":false},"device_limits":{"camera":10,"chime":5,"doorbell_button":2,"owl":10,"siren":5,"total_devices":20},"whats_new":{"updated_at":20200924,"url":"https://updates.blinkforhome.com/"}}
[10/31/2020, 11:44:09] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:44:09] [Blink] 200 OK
[10/31/2020, 11:44:09] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:44:09 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': '1jXhmxQktQTIm4vMQ_D1xwbrgF0jc9b7lLjtOYKhJiE4El58KG_dXA==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-0b2944c3a6ef0bbe7',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:44:09] [Blink] {"account":{"id":80325,"email_verified":true,"email_verification_required":true},"networks":[{"id":103215,"created_at":"2019-06-28T12:26:40+00:00","updated_at":"2020-10-30T16:27:55+00:00","name":"StationHome","time_zone":"Europe/Berlin","dst":true,"armed":true,"lv_save":false}],"sync_modules":[{"id":320349,"created_at":"2019-10-11T16:08:36+00:00","updated_at":"2020-10-31T10:13:21+00:00","onboarded":true,"status":"online","name":"My Blink Sync Module","serial":"XXXXXXXX","fw_version":"2.13.26","type":"sm1","last_hb":"2020-10-31T10:43:23+00:00","wifi_strength":4,"network_id":103215,"enable_temp_alerts":true,"local_storage_enabled":false,"local_storage_compatible":false,"local_storage_status":"unavailable"}],"cameras":[{"id":546462,"created_at":"2020-04-01T16:49:18+00:00","updated_at":"2020-10-31T09:55:54+00:00","name":"Blinker 1","serial":"681146121","fw_version":"2.151","type":"xt","enabled":false,"thumbnail":"/media/production/account/80325/network/103215/camera/546462/clip_LzawD7JN_2020_10_30__20_22PM","status":"done","battery":"ok","usage_rate":false,"network_id":103215,"issues":[],"signals":{"lfr":5,"wifi":2,"temp":67,"battery":3},"local_storage_enabled":false,"local_storage_compatible":false}],"sirens":[],"chimes":[],"video_stats":{"storage":0,"auto_delete_days":14,"auto_delete_day_options":[3,7,14,30,365]},"doorbell_buttons":[],"owls":[],"app_updates":{"message":"OK","code":103,"update_available":false,"update_required":false},"device_limits":{"camera":10,"chime":5,"doorbell_button":2,"owl":10,"siren":5,"total_devices":20},"whats_new":{"updated_at":20200924,"url":"https://updates.blinkforhome.com/"}}
[10/31/2020, 11:44:09] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:44:09] [Blink] 200 OK
[10/31/2020, 11:44:09] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:44:09 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': '743WakhYaGiNIbCWNM69KwR8QSsACTOvbTYrh13PiLDNjzPa_7O17g==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-002bcd32acc9df6e1',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:44:09] [Blink] {"limit":500,"purge_id":991893923,"refresh_count":0,"media":[]}
[10/31/2020, 11:44:19] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:44:19] [Blink] 200 OK
[10/31/2020, 11:44:19] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:44:19 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'tmOtjOYbgpDoozTnLGVPqeAQ7fUOrUe5hA15qnMmKDAwRQIBZIPdRg==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-002bcd32acc9df6e1',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:44:19] [Blink] {"account":{"id":80325,"email_verified":true,"email_verification_required":true},"networks":[{"id":103215,"created_at":"2019-06-28T12:26:40+00:00","updated_at":"2020-10-30T16:27:55+00:00","name":"StationHome","time_zone":"Europe/Berlin","dst":true,"armed":true,"lv_save":false}],"sync_modules":[{"id":320349,"created_at":"2019-10-11T16:08:36+00:00","updated_at":"2020-10-31T10:13:21+00:00","onboarded":true,"status":"online","name":"My Blink Sync Module","serial":"XXXXXXXX","fw_version":"2.13.26","type":"sm1","last_hb":"2020-10-31T10:43:23+00:00","wifi_strength":4,"network_id":103215,"enable_temp_alerts":true,"local_storage_enabled":false,"local_storage_compatible":false,"local_storage_status":"unavailable"}],"cameras":[{"id":546462,"created_at":"2020-04-01T16:49:18+00:00","updated_at":"2020-10-31T09:55:54+00:00","name":"Blinker 1","serial":"681146121","fw_version":"2.151","type":"xt","enabled":false,"thumbnail":"/media/production/account/80325/network/103215/camera/546462/clip_LzawD7JN_2020_10_30__20_22PM","status":"done","battery":"ok","usage_rate":false,"network_id":103215,"issues":[],"signals":{"lfr":5,"wifi":2,"temp":67,"battery":3},"local_storage_enabled":false,"local_storage_compatible":false}],"sirens":[],"chimes":[],"video_stats":{"storage":0,"auto_delete_days":14,"auto_delete_day_options":[3,7,14,30,365]},"doorbell_buttons":[],"owls":[],"app_updates":{"message":"OK","code":103,"update_available":false,"update_required":false},"device_limits":{"camera":10,"chime":5,"doorbell_button":2,"owl":10,"siren":5,"total_devices":20},"whats_new":{"updated_at":20200924,"url":"https://updates.blinkforhome.com/"}}
[10/31/2020, 11:44:29] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:44:29] [Blink] 200 OK
[10/31/2020, 11:44:29] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:44:29 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'DQgGb-mAXrAmjm90YzDqYKGpxfoVekDn_olVwR-NC-qF_msLEBpVSw==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-00db64ff2b4d27031',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:44:29] [Blink] {"account":{"id":80325,"email_verified":true,"email_verification_required":true},"networks":[{"id":103215,"created_at":"2019-06-28T12:26:40+00:00","updated_at":"2020-10-30T16:27:55+00:00","name":"StationHome","time_zone":"Europe/Berlin","dst":true,"armed":true,"lv_save":false}],"sync_modules":[{"id":320349,"created_at":"2019-10-11T16:08:36+00:00","updated_at":"2020-10-31T10:13:21+00:00","onboarded":true,"status":"online","name":"My Blink Sync Module","serial":"XXXXXXXX","fw_version":"2.13.26","type":"sm1","last_hb":"2020-10-31T10:44:24+00:00","wifi_strength":4,"network_id":103215,"enable_temp_alerts":true,"local_storage_enabled":false,"local_storage_compatible":false,"local_storage_status":"unavailable"}],"cameras":[{"id":546462,"created_at":"2020-04-01T16:49:18+00:00","updated_at":"2020-10-31T09:55:54+00:00","name":"Blinker 1","serial":"681146121","fw_version":"2.151","type":"xt","enabled":false,"thumbnail":"/media/production/account/80325/network/103215/camera/546462/clip_LzawD7JN_2020_10_30__20_22PM","status":"done","battery":"ok","usage_rate":false,"network_id":103215,"issues":[],"signals":{"lfr":5,"wifi":2,"temp":67,"battery":3},"local_storage_enabled":false,"local_storage_compatible":false}],"sirens":[],"chimes":[],"video_stats":{"storage":0,"auto_delete_days":14,"auto_delete_day_options":[3,7,14,30,365]},"doorbell_buttons":[],"owls":[],"app_updates":{"message":"OK","code":103,"update_available":false,"update_required":false},"device_limits":{"camera":10,"chime":5,"doorbell_button":2,"owl":10,"siren":5,"total_devices":20},"whats_new":{"updated_at":20200924,"url":"https://updates.blinkforhome.com/"}}
[10/31/2020, 11:44:29] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:44:29] [Blink] 200 OK
[10/31/2020, 11:44:29] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:44:29 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'kuSf-ShpdguhLxmxiRMv21-eGIyWXVdlmYgNk3uOjqKpv2b2i-BBOg==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-0be600a9e21cba1ec',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:44:29] [Blink] {"limit":500,"purge_id":991893923,"refresh_count":0,"media":[]}
[10/31/2020, 11:44:39] [Blink] {
  method: 'GET',
  headers: {
    'User-Agent': 'Blink/8854 CFNetwork/1202 Darwin/20.1.0',
    'app-build': 'IOS_8854',
    Locale: 'en_US',
    'accept-language': 'en_US',
    Accept: '*/*',
    TOKEN_AUTH: 'yVhDF3m2z_r9CBzkq3_6iQ'
  },
  agent: [Function: agent]
}
[10/31/2020, 11:44:39] [Blink] 200 OK
[10/31/2020, 11:44:39] [Blink] {
  connection: 'keep-alive',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  date: 'Sat, 31 Oct 2020 10:44:39 GMT',
  server: 'nginx + Phusion Passenger',
  status: '200 OK',
  'transfer-encoding': 'chunked',
  vary: 'Accept-Encoding',
  via: '1.1 25fe70cc18ad9b2503949e3460083641.cloudfront.net (CloudFront)',
  'x-amz-cf-id': 'pixrlwOmMPrGjY-r5E6l0_0tyVulQFn-SGof_z2Jg9T164eKJzeceg==',
  'x-amz-cf-pop': 'AMS54-C1',
  'x-blink-served-by': 'i-00a1cdfd6c13e2c78',
  'x-cache': 'Miss from cloudfront',
  'x-content-type-options': 'nosniff',
  'x-powered-by': 'Phusion Passenger'
}
[10/31/2020, 11:44:39] [Blink] {"account":{"id":80325,"email_verified":true,"email_verification_required":true},"networks":[{"id":103215,"created_at":"2019-06-28T12:26:40+00:00","updated_at":"2020-10-30T16:27:55+00:00","name":"StationHome","time_zone":"Europe/Berlin","dst":true,"armed":true,"lv_save":false}],"sync_modules":[{"id":320349,"created_at":"2019-10-11T16:08:36+00:00","updated_at":"2020-10-31T10:13:21+00:00","onboarded":true,"status":"online","name":"My Blink Sync Module","serial":"XXXXXXXX","fw_version":"2.13.26","type":"sm1","last_hb":"2020-10-31T10:44:24+00:00","wifi_strength":4,"network_id":103215,"enable_temp_alerts":true,"local_storage_enabled":false,"local_storage_compatible":false,"local_storage_status":"unavailable"}],"cameras":[{"id":546462,"created_at":"2020-04-01T16:49:18+00:00","updated_at":"2020-10-31T09:55:54+00:00","name":"Blinker 1","serial":"681146121","fw_version":"2.151","type":"xt","enabled":false,"thumbnail":"/media/production/account/80325/network/103215/camera/546462/clip_LzawD7JN_2020_10_30__20_22PM","status":"done","battery":"ok","usage_rate":false,"network_id":103215,"issues":[],"signals":{"lfr":5,"wifi":2,"temp":67,"battery":3},"local_storage_enabled":false,"local_storage_compatible":false}],"sirens":[],"chimes":[],"video_stats":{"storage":0,"auto_delete_days":14,"auto_delete_day_options":[3,7,14,30,365]},"doorbell_buttons":[],"owls":[],"app_updates":{"message":"OK","code":103,"update_available":false,"update_required":false},"device_limits":{"camera":10,"chime":5,"doorbell_button":2,"owl":10,"siren":5,"total_devices":20},"whats_new":{"updated_at":20200924,"url":"https://updates.blinkforhome.com/"}}

**Comment by m0v1em4n** [comment]
Same issue here since updating to the latest, was ok previously

**Comment by colinbendell** [comment]
fat fingers fixed. gotta get a CI system in place. should be fixed now.

**Comment by vdrover** [comment]
Thumbnails working well.

**Comment by Ron0815** [comment]
Unfortunately the update in version 3.5.13 did not solve my problem. The image is still not updated/refreshed after the first start.
