### ISSUE TITLE
Plugin support for homebridge 1.3 beta

### ISSUE THREAD

**Issue by mdiskin** [colinbendell/homebridge-blink-for-home#44]
After upgrading the blink plugin is no longer working.

[1/19/2021, 10:20:45 AM] [Blink] Initing: Blink:Network:64339
[1/19/2021, 10:20:45 AM] [Blink] TypeError: this.enqueueConfigurationUpdate is not a function
    at PlatformAccessory.Accessory.addService (C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:444:12)
    at BlinkNetwork.createAccessory (C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-blink-for-home\src\blink.js:195:37)
    at C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-blink-for-home\src\index.js:54:60
    at Array.map (<anonymous>)
    at HomebridgeBlink.init (C:\Users\DVR\AppData\Roaming\npm\node_modules\homebridge-blink-for-home\src\index.js:54:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[1/19/2021, 10:20:45 AM] [Blink] NOTE: Blink devices in HomeKit will not be responsive.

**Comment by donavanbecker** [comment]
same here:

```
[2/6/2021, 11:09:41 PM] [Blink] TypeError: this.enqueueConfigurationUpdate is not a function
    at PlatformAccessory.Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:444:12)
    at BlinkNetwork.createAccessory (/usr/lib/node_modules/@donavanbecker/homebridge-blink-for-home/src/blink.js:262:35)
    at /usr/lib/node_modules/@donavanbecker/homebridge-blink-for-home/src/index.js:54:60
    at Array.map (<anonymous>)
    at HomebridgeBlink.init (/usr/lib/node_modules/@donavanbecker/homebridge-blink-for-home/src/index.js:54:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2/6/2021, 11:09:41 PM] [Blink] NOTE: Blink devices in HomeKit will not be responsive.
```

**Comment by colinbendell** [comment]
fixed. This was a legacy hold over from the early days of the HAP interface

**Comment by rweckhoff** [comment]
How does one get the fix? 3.6.2 shows as the latest. Still have the error on 1.3.0 beta 54.

**Comment by rweckhoff** [comment]
> fixed. This was a legacy hold over from the early days of the HAP interface

How does one get the fix? 3.6.2 shows as the latest. Still have the error on 1.3.0 betas.

**Comment by WhooKnew** [comment]
[20/02/2021, 08:38:29] [Blink] TypeError: this.enqueueConfigurationUpdate is not a function
    at PlatformAccessory.Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:466:12)
    at BlinkNetwork.createAccessory (/usr/local/lib/node_modules/homebridge-blink-for-home/src/blink.js:195:37)
    at /usr/local/lib/node_modules/homebridge-blink-for-home/src/index.js:54:60
    at Array.map (<anonymous>)
    at HomebridgeBlink.init (/usr/local/lib/node_modules/homebridge-blink-for-home/src/index.js:54:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[20/02/2021, 08:38:29] [Blink] NOTE: Blink devices in HomeKit will not be responsive.


I get this failure.
Can anybody please help ?

Thank You

BR

Andreas

**Comment by colinbendell** [comment]
fixed in v3.7.0
